<?php
declare(strict_types=1);

namespace vyuziuk\EasyKits\i18n;

use pocketmine\lang\BaseLang;
use pocketmine\utils\TextFormat;
use vyuziuk\EasyKits\Main;

class Language extends BaseLang{
    public function __construct(string $lang){
        $path = Main::getInstance()->getDataFolder() . LanguageFactory::DIRECTORY . DIRECTORY_SEPARATOR;
        parent::__construct($lang, $path, LanguageFactory::FALLBACK);
    }

    public function translateString(string $str, array $params = [], string $onlyPrefix = null): string{
        return TextFormat::colorize(parent::translateString($str, $params, $onlyPrefix)); // TODO: Change the autogenerated stub
    }
}